-- ====================================================================================
--              PHẦN 1: TẠO BẢNG VÀ CONSTRAINT
-- ====================================================================================

-- 1. Bảng THAMSO
CREATE TABLE THAMSO (
    MaTS VARCHAR2(10) PRIMARY KEY,
    TenTS NVARCHAR2(100) UNIQUE,
    GiaTri NUMBER(12,2),
    MoTa NVARCHAR2(500)
);

-- 2. Bảng THONGBAO
CREATE TABLE THONGBAO (
    MaTB VARCHAR2(10) PRIMARY KEY,
    LoaiTB NVARCHAR2(20),
    NoiDung NVARCHAR2(500),
    TrangThaiTB NUMBER(1) DEFAULT 0,      -- 0: Chưa đọc, 1: Đã đọc
    TGTao DATE DEFAULT SYSDATE
);

-- 3. Bảng TAIKHOAN
CREATE TABLE TAIKHOAN (
    Username NVARCHAR2(50) PRIMARY KEY,
    Password VARCHAR2(255) NOT NULL,
    LoaiTK NUMBER(1) CHECK (LoaiTK IN (0, 1, 2)), -- 0: Quản lý, 1: Nhân viên, 2: Khách hàng
    TrangThaiTK NUMBER(1) CHECK (TrangThaiTK IN (0, 1)), -- 0: Bị khoá, 1: Hoạt động
    TGTao DATE DEFAULT SYSDATE
);

-- 4. Bảng KHACHHANG
CREATE TABLE KHACHHANG (
    MaKH VARCHAR2(10) PRIMARY KEY,
    Username NVARCHAR2(50),
    TenKH NVARCHAR2(100),
    LoaiKH NVARCHAR2(50) CHECK (LoaiKH IN ('Thường','VIP')),
    DiaChi NVARCHAR2(255),
    SDT VARCHAR2(12),
    Email NVARCHAR2(100),
    CONSTRAINT FK_KH_TAIKHOAN FOREIGN KEY (Username) REFERENCES TAIKHOAN(Username)
);

-- 5. Bảng NHANVIEN
CREATE TABLE NHANVIEN (
    MaNV VARCHAR2(10) PRIMARY KEY,
    Username NVARCHAR2(50),
    TenNV NVARCHAR2(100),
    ChucVu NVARCHAR2(50) CHECK (ChucVu IN ('NV thu mua', 'NV kho', 'NV giao hàng')),
    SDT VARCHAR2(12),
    Luong NUMBER(12,2),
    CONSTRAINT FK_NV_TAIKHOAN FOREIGN KEY (Username) REFERENCES TAIKHOAN(Username)
);

-- 6. Bảng NHACUNGCAP
CREATE TABLE NHACUNGCAP (
    MaNCC VARCHAR2(10) PRIMARY KEY,
    TenNCC NVARCHAR2(100),
    DiaChi NVARCHAR2(255),
    SDT VARCHAR2(12),
    Email VARCHAR2(100),
    ChungNhanCL VARCHAR2(100),
    TrangThaiHopTac NUMBER(1) CHECK (TrangThaiHopTac IN (0, 1)) -- 0: Ngừng hợp tác, 1: Đang hợp tác
);

-- 7. Bảng LOAISANPHAM
CREATE TABLE LOAISANPHAM (
    MaLSP VARCHAR2(10) PRIMARY KEY,
    TenLSP NVARCHAR2(100),
    MoTa NVARCHAR2(500)
);

-- 8. Bảng SANPHAM
CREATE TABLE SANPHAM (
    MaSP VARCHAR2(10) PRIMARY KEY,
    TenSP NVARCHAR2(100),
    MaLSP VARCHAR2(10),
    ChatLuong NVARCHAR2(100) CHECK (ChatLuong IN ('Loại 1', 'Loại 2', 'Loại 3')),
    GiaMua NUMBER(12,2),
    GiaBan NUMBER(12,2),
    DonViTinh NVARCHAR2(20),
    BaoQuan NVARCHAR2(100) CHECK (BaoQuan IN ('Mát', 'Lạnh', 'Đông')),
    HinhAnh NVARCHAR2(200),
    CONSTRAINT FK_SP_LSP FOREIGN KEY (MaLSP) REFERENCES LOAISANPHAM(MaLSP)
);

-- 9. Bảng KHO
CREATE TABLE KHO (
    MaKho VARCHAR2(10) PRIMARY KEY,
    TenKho NVARCHAR2(100),
    LoaiKho NVARCHAR2(100) CHECK (LoaiKho IN ('Mát', 'Lạnh', 'Đông')),
    DiaChi NVARCHAR2(255),
    MoTa NVARCHAR2(500)
);

-- 10. Bảng LICHSUGIA
CREATE TABLE LICHSUGIA (
    MaGia VARCHAR2(10) PRIMARY KEY,
    MaSP VARCHAR2(10),
    GiaMua NUMBER(12,2),
    GiaBan NUMBER(12,2),
    TGApDung DATE DEFAULT SYSDATE,
    CONSTRAINT FK_LSG_SP FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

-- 11. Bảng LOHANG
CREATE TABLE LOHANG (
    MaLH VARCHAR2(10) PRIMARY KEY,
    MaNCC VARCHAR2(10),
    MaNV VARCHAR2(10),
    TGNhap DATE DEFAULT SYSDATE,
    TongTien NUMBER(12,2) DEFAULT 0 CHECK (TongTien >= 0),
    TrangThaiLH NVARCHAR2(50) DEFAULT 'Chờ kiểm duyệt' CHECK (TrangThaiLH IN ('Chờ kiểm duyệt', 'Đã nhập kho')),
    CONSTRAINT FK_LH_NCC FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC),
    CONSTRAINT FK_LH_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);

-- 12. Bảng CHITIETLOHANG
CREATE TABLE CHITIETLOHANG (
    MaCTLH VARCHAR2(10) PRIMARY KEY,
    MaLH VARCHAR2(10),
    MaSP VARCHAR2(10),
    GiaMua NUMBER(12,2) CHECK (GiaMua > 0),
    SoLuong NUMBER(10,2) CHECK (SoLuong > 0),
    ThanhTien NUMBER(12,2) CHECK (ThanhTien > 0),
    CONSTRAINT FK_CTLH_LH FOREIGN KEY (MaLH) REFERENCES LOHANG(MaLH),
    CONSTRAINT FK_CTLH_SP FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

-- 13. Bảng TONKHO
CREATE TABLE TONKHO (
    MaTonKho VARCHAR2(10) PRIMARY KEY,
    MaKho VARCHAR2(10),
    MaCTLH VARCHAR2(10),
    SLConLai NUMBER(10,2) CHECK (SLConLai >= 0),
    SLKhaDung NUMBER(10,2) CHECK (SLKhaDung >= 0),
    TGNhapKho DATE DEFAULT SYSDATE,
    TGHetHan DATE,
    ViTri NVARCHAR2(100),
    CONSTRAINT FK_TK_KHO FOREIGN KEY (MaKho) REFERENCES KHO(MaKho),
    CONSTRAINT FK_TK_CTLH FOREIGN KEY (MaCTLH) REFERENCES CHITIETLOHANG(MaCTLH),
    CONSTRAINT CK_TGHetHan CHECK (TGHetHan >= TGNhapKho)
);

-- 14. Bảng DONHANG
CREATE TABLE DONHANG (
    MaDH VARCHAR2(10) PRIMARY KEY,
    MaKH VARCHAR2(10),
    MaNV VARCHAR2(10),
    TGDat DATE DEFAULT SYSDATE,
    TGGiaoDK DATE,
    DiaChiGiaoHang NVARCHAR2(255),
    PhiVanChuyen NUMBER(12,2) CHECK (PhiVanChuyen >= 0),
    TongTien NUMBER(12,2) DEFAULT 0 CHECK (TongTien >= 0),
    TrangThaiDH NVARCHAR2(50) DEFAULT 'Đã đặt' CHECK (TrangThaiDH IN ('Đã đặt', 'Chờ thanh toán', 'Đã thanh toán', 'Đang giao', 'Hoàn thành', 'Đã huỷ')),
    CONSTRAINT FK_DH_KH FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    CONSTRAINT FK_DH_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT CK_TGGiaoDK CHECK (TGGiaoDK >= TGDat)
);

-- 15. Bảng CHITIETDONHANG
CREATE TABLE CHITIETDONHANG (
    MaCTDH VARCHAR2(10) PRIMARY KEY,
    MaDH VARCHAR2(10),
    MaSP VARCHAR2(10),
    GiaBan NUMBER(12,2) CHECK (GiaBan > 0),
    SoLuong NUMBER(10,2) CHECK (SoLuong > 0),
    ThanhTien NUMBER(12,2) CHECK (ThanhTien > 0),
    CONSTRAINT FK_CTDH_DH FOREIGN KEY (MaDH) REFERENCES DONHANG(MaDH),
    CONSTRAINT FK_CTDH_SP FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

-- 16. Bảng XUATKHO
CREATE TABLE XUATKHO (
    MaXK VARCHAR2(10) PRIMARY KEY,
    MaCTDH VARCHAR2(10),
    MaTonKho VARCHAR2(10),
    MaNV VARCHAR2(10),
    SLXuat NUMBER(10,2) CHECK (SLXuat > 0),
    TGCapNhat DATE DEFAULT SYSDATE,
    TrangThaiXK NVARCHAR2(50) DEFAULT 'Tạm giữ' CHECK (TrangThaiXK IN ('Tạm giữ', 'Đã xuất')),
    CONSTRAINT FK_XK_CTDH FOREIGN KEY (MaCTDH) REFERENCES CHITIETDONHANG(MaCTDH),
    CONSTRAINT FK_XK_TonKho FOREIGN KEY (MaTonKho) REFERENCES TONKHO(MaTonKho),
    CONSTRAINT FK_XK_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);