-- ====================================================================================
--           PHẦN 2: Tạo SEQUENCE và trigger tự động sinh mã cho khoá chính
-- ====================================================================================

CREATE SEQUENCE SEQ_THAMSO START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_THONGBAO START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_KHACHHANG START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NHANVIEN START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NHACUNGCAP START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LOAISANPHAM START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SANPHAM START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_KHO START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LICHSUGIA START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LOHANG START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TONKHO START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DONHANG START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_XUATKHO START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 1. THAMSO
CREATE OR REPLACE TRIGGER TRG_THAMSO_ID 
BEFORE INSERT ON THAMSO 
FOR EACH ROW 
BEGIN IF :NEW.MaTS IS NULL THEN :NEW.MaTS := 'TS' || LPAD(SEQ_THAMSO.NEXTVAL,6,'0'); END IF; END;
/

-- 2. THONGBAO
CREATE OR REPLACE TRIGGER TRG_THONGBAO_ID 
BEFORE INSERT ON THONGBAO 
FOR EACH ROW 
BEGIN IF :NEW.MaTB IS NULL THEN :NEW.MaTB := 'TB' || LPAD(SEQ_THONGBAO.NEXTVAL,6,'0'); END IF; END;
/

-- 3. KHACHHANG
CREATE OR REPLACE TRIGGER TRG_KHACHHANG_ID 
BEFORE INSERT ON KHACHHANG 
FOR EACH ROW 
BEGIN 
IF :NEW.MaKH IS NULL THEN :NEW.MaKH := 'KH' || LPAD(SEQ_KHACHHANG.NEXTVAL,6,'0'); END IF; 
END;
/

-- 4. NHANVIEN
CREATE OR REPLACE TRIGGER TRG_NHANVIEN_ID 
BEFORE INSERT ON NHANVIEN 
FOR EACH ROW 
BEGIN 
IF :NEW.MaNV IS NULL THEN :NEW.MaNV := 'NV' || LPAD(SEQ_NHANVIEN.NEXTVAL,6,'0'); END IF; 
END;
/

-- 5. NHACUNGCAP
CREATE OR REPLACE TRIGGER TRG_NCC_ID 
BEFORE INSERT ON NHACUNGCAP 
FOR EACH ROW 
BEGIN 
IF :NEW.MaNCC IS NULL THEN :NEW.MaNCC := 'NCC' || LPAD(SEQ_NHACUNGCAP.NEXTVAL,5,'0'); END IF; 
END;
/

-- 6. LOAISANPHAM
CREATE OR REPLACE TRIGGER TRG_LSP_ID 
BEFORE INSERT ON LOAISANPHAM 
FOR EACH ROW 
BEGIN 
IF :NEW.MaLSP IS NULL THEN :NEW.MaLSP := 'LSP' || LPAD(SEQ_LOAISANPHAM.NEXTVAL,5,'0'); END IF; 
END;
/

-- 7. SANPHAM
CREATE OR REPLACE TRIGGER TRG_SANPHAM_ID 
BEFORE INSERT ON SANPHAM 
FOR EACH ROW 
BEGIN 
IF :NEW.MaSP IS NULL THEN :NEW.MaSP := 'SP' || LPAD(SEQ_SANPHAM.NEXTVAL,6,'0'); END IF; 
END;
/

-- 8. KHO
CREATE OR REPLACE TRIGGER TRG_KHO_ID 
BEFORE INSERT ON KHO 
FOR EACH ROW 
BEGIN 
IF :NEW.MaKho IS NULL THEN :NEW.MaKho := 'KHO' || LPAD(SEQ_KHO.NEXTVAL,5,'0'); END IF; 
END;
/

-- 9. LICHSUGIA
CREATE OR REPLACE TRIGGER TRG_LSG_ID 
BEFORE INSERT ON LICHSUGIA 
FOR EACH ROW 
BEGIN 
IF :NEW.MaGia IS NULL THEN :NEW.MaGia := 'GIA' || LPAD(SEQ_LICHSUGIA.NEXTVAL,5,'0'); END IF; 
END;
/

-- 10. LOHANG
CREATE OR REPLACE TRIGGER TRG_LOHANG_ID 
BEFORE INSERT ON LOHANG 
FOR EACH ROW 
BEGIN 
IF :NEW.MaLH IS NULL THEN :NEW.MaLH := 'LH' || LPAD(SEQ_LOHANG.NEXTVAL,6,'0'); END IF; 
END;
/


-- 12. TONKHO
CREATE OR REPLACE TRIGGER TRG_TONKHO_ID 
BEFORE INSERT ON TONKHO 
FOR EACH ROW 
BEGIN 
IF :NEW.MaTonKho IS NULL THEN :NEW.MaTonKho := 'TK' || LPAD(SEQ_TONKHO.NEXTVAL,6,'0'); END IF; 
END;
/

-- 13. DONHANG
CREATE OR REPLACE TRIGGER TRG_DONHANG_ID 
BEFORE INSERT ON DONHANG 
FOR EACH ROW 
BEGIN 
IF :NEW.MaDH IS NULL THEN :NEW.MaDH := 'DH' || LPAD(SEQ_DONHANG.NEXTVAL,6,'0'); END IF; 
END;
/


-- 15. XUATKHO
CREATE OR REPLACE TRIGGER TRG_XUATKHO_ID 
BEFORE INSERT ON XUATKHO 
FOR EACH ROW 
BEGIN 
IF :NEW.MaXK IS NULL THEN :NEW.MaXK := 'XK' || LPAD(SEQ_XUATKHO.NEXTVAL,6,'0'); END IF; 
END;
/